//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pace.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pace.Server.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse….
        /// </summary>
        public static string FileExplorer_Browse {
            get {
                return ResourceManager.GetString("FileExplorer_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string FileExplorer_Delete {
            get {
                return ResourceManager.GetString("FileExplorer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FileExplorer_Name {
            get {
                return ResourceManager.GetString("FileExplorer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileExplorer_Open {
            get {
                return ResourceManager.GetString("FileExplorer_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string FileExplorer_Properties {
            get {
                return ResourceManager.GetString("FileExplorer_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string FileExplorer_Rename {
            get {
                return ResourceManager.GetString("FileExplorer_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FileExplorer_Size {
            get {
                return ResourceManager.GetString("FileExplorer_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FileExplorer_Type {
            get {
                return ResourceManager.GetString("FileExplorer_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileType_File {
            get {
                return ResourceManager.GetString("FileType_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string FileType_Folder {
            get {
                return ResourceManager.GetString("FileType_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string Main_Address {
            get {
                return ResourceManager.GetString("Main_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client connected from {0}..
        /// </summary>
        public static string Main_ClientConnected {
            get {
                return ResourceManager.GetString("Main_ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Prompt.
        /// </summary>
        public static string Main_CommandPrompt {
            get {
                return ResourceManager.GetString("Main_CommandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Name.
        /// </summary>
        public static string Main_ComputerName {
            get {
                return ResourceManager.GetString("Main_ComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager.
        /// </summary>
        public static string Main_FileManager {
            get {
                return ResourceManager.GetString("Main_FileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Main_Identifier {
            get {
                return ResourceManager.GetString("Main_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Main_Management {
            get {
                return ResourceManager.GetString("Main_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string Main_OperatingSystem {
            get {
                return ResourceManager.GetString("Main_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Main_Port {
            get {
                return ResourceManager.GetString("Main_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveillance.
        /// </summary>
        public static string Main_Surveillance {
            get {
                return ResourceManager.GetString("Main_Surveillance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Screenshot.
        /// </summary>
        public static string Main_TakeScreenshot {
            get {
                return ResourceManager.GetString("Main_TakeScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Main_Username {
            get {
                return ResourceManager.GetString("Main_Username", resourceCulture);
            }
        }
    }
}
